
spring:
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  datasource:
    url: jdbc:mysql://localhost:8889/KnowledgeBase
    username: root
    password: root


  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 731140942694-vtus1fn8u0m1acv803g8q51mnpct8n3d.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
          facebook:
            client-id: 4978756288905349
            clientSecret: cd5cb7ff16ca451715d5e961f752a6b2
            scope:
              - email
  jpa:

    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect=org:
          hibernate:
            search:
              backend:
                directory:
                  root = articles/index
            dialect: MySQL5InnoDBDialect
  mail:
    host: localhost
    port: 1025
    username: "hello"
    password: "hello"
    properties:
        mail:
          smtp:
            ssl:
              trust: "*"
            auth: false
            starttls:
              enable: false
            connection-timeout: 5000
            timeout: 3000
            write-timeout: 5000
  config:
    activate:
      on-profile: