
server:
  forward-headers-strategy: NATIVE
access:
  key:
    id: 
    secret: 
s3:
  region:
    name: eu-west-2
  bucket:
    name: showcase-persist
spring:

  h2:
    console.enabled: true
  servlet:
    multipart:
      max-file-size: 80MB
      max-request-size: 80MB
  datasource:
    url: jdbc:mysql://localhost:3306/site
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: rootpassword

#  datasource:
#    url: jdbc:mysql://localhost:8889/socialsite
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver


  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 
            clientSecret: 
            scope:
              - user:email
              - email
              - read:user
          google:
            clientId: 
            clientSecret: 
            scope:
              - email
          facebook:
            client-id: 
            clientSecret: 
            scope:
              - email
              - public_profile

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:

      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        search:
          backend:
            directory: root = posts/index

  config:
    activate:
      on-profile:
