
spring:
  h2:
    console.enabled: true
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

#  datasource:
#    url: jdbc:mysql://localhost:8889/socialsite
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver


  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 731140942694-vtus1fn8u0m1acv803g8q51mnpct8n3d.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
          facebook:
            client-id: 4978756288905349
            clientSecret: cd5cb7ff16ca451715d5e961f752a6b2
            scope:
              - email
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:

      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        search:
          backend:
            directory: root = posts/index

  config:
    activate:
      on-profile: